
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: auth-service
  name: auth-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: auth-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: auth-service
    spec:
      containers:
      - image: auth-service:v1
        imagePullPolicy: Always
        name: auth-service
        env:
        - name: SECRET
          value: birdiebirdiebirdie
        ports:
        - containerPort: 8080
          name: http-api
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  authentication
      config:
        auth_service: "auth-service:3000"
spec:
  type: ClusterIP
  selector:
    run: auth-service
  ports:
  - port: 3000
    name: auth-service
    targetPort: http-api