---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: social-service
  name: social-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: social-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: social-service
    spec:
      containers:
      - image: vilellaj/adviser-social-service:latest
        imagePullPolicy: IfNotPresent
        name: social-service
        env:
          - name: POST_SERVICE_URI
            value: http://post-service.default.svc.cluster.local
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: social-service
  name: social-service
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  social-service_mapping
      prefix: /social
      rewrite: /api/social
      service: social-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: social-service
  sessionAffinity: None
  type: ClusterIP
