---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: user-service
  name: user-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: user-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: user-service
    spec:
      containers:
      - image: user-service:v2
        imagePullPolicy: IfNotPresent
        name: user-service
        env:
          - name: MONGO_URI
            value: mongodb://adviser:4dv1s3r@ds133875.mlab.com:33875/adviser
          - name: SECRET
            value: birdiebirdiebirdie
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: user-service
  name: user-service
  namespace: default
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  user-service_mapping
      prefix: /users
      rewrite: /api/users
      service: user-service
      bypass_auth: true
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: user-service
  sessionAffinity: None
  type: ClusterIP
